---
name: 🐛 Bug Report
about: Create a report to help us improve zuki
title: '[BUG] '
labels: ['bug', 'needs-triage']
assignees: ''
---

## Bug Description

**Describe the bug**
A clear and concise description of what the bug is.

**Expected Behavior**
A clear and concise description of what you expected to happen.

**Actual Behavior**
A clear and concise description of what actually happened.

## Reproduction

**Steps to Reproduce**
1. Go to '...'
2. Run command '...'
3. See error

**Minimal Reproduction Case**
```zig
// Please provide a minimal code example that reproduces the issue
const std = @import("std");

pub fn main() void {
    // Your reproduction code here
}
```

**Is the issue reproducible?**
- [ ] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable to reproduce

## Environment

**System Information:**
- OS: [e.g., Windows 11, macOS 13.0, Ubuntu 22.04]
- Architecture: [e.g., x86_64, aarch64]
- Zig Version: [e.g., 0.12.0]
- zuki Version: [e.g., 0.1.0]

**Build Configuration:**
- Build Mode: [e.g., Debug, ReleaseFast, ReleaseSafe, ReleaseSmall]
- Target: [e.g., native, x86_64-windows, etc.]

## Additional Context

**Error Messages/Logs**
```
// Please include any error messages, stack traces, or relevant logs
```

**Workarounds**
If you found any workarounds, please describe them here.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional Information**
Add any other context about the problem here.

## Checklist

- [ ] I have searched existing issues to ensure this is not a duplicate
- [ ] I have provided a minimal reproduction case
- [ ] I have included all relevant environment information
- [ ] I have checked that this issue exists on the latest version
