name: 📚 Documentation Issue
description: Report an issue with documentation or request documentation improvements
title: "[DOCS] "
labels: ["documentation", "good-first-issue"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping improve our documentation! Please provide details about the documentation issue.

  - type: dropdown
    id: issue-type
    attributes:
      label: Type of documentation issue
      multiple: true
      options:
        - Missing documentation
        - Incorrect/outdated information
        - Unclear or confusing content
        - Broken links
        - Typos or grammar issues
        - Missing examples
        - API documentation missing
        - Tutorial needed
    validations:
      required: true

  - type: checkboxes
    id: location
    attributes:
      label: Where is the documentation issue?
      options:
        - label: README.md
        - label: CONTRIBUTING.md
        - label: API documentation (inline comments)
        - label: Code examples
        - label: Other (specify below)

  - type: input
    id: specific-location
    attributes:
      label: Specific location
      description: File name, section name, line numbers, or URL if applicable
      placeholder: e.g., README.md line 42, or https://example.com/docs
    validations:
      required: true

  - type: textarea
    id: issue-description
    attributes:
      label: What's wrong or missing?
      description: A clear description of the documentation issue.
    validations:
      required: true

  - type: textarea
    id: current-docs
    attributes:
      label: Current documentation (if any)
      description: Copy the current documentation text here if it exists but is incorrect.
      render: markdown
    validations:
      required: false

  - type: textarea
    id: expected-docs
    attributes:
      label: Expected documentation
      description: What should the documentation say instead?
    validations:
      required: true

  - type: textarea
    id: proposed-content
    attributes:
      label: Proposed content
      description: Your suggested documentation content.
      render: markdown
    validations:
      required: false

  - type: checkboxes
    id: target-audience
    attributes:
      label: Who would benefit from this documentation?
      options:
        - label: New users getting started
        - label: Experienced users learning advanced features
        - label: Contributors to the project
        - label: API consumers
        - label: Other (specify in additional context)

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe the scenario where someone would need this documentation.
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - "Low - Nice to have"
        - "Medium - Important for user experience"
        - "High - Blocking users from using the feature"
    validations:
      required: true

  - type: dropdown
    id: complexity
    attributes:
      label: Complexity
      options:
        - "Simple - Minor edit or addition"
        - "Medium - New section or significant rewrite"
        - "Complex - Major documentation overhaul needed"
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Links to related documentation, external resources, or examples from similar projects.
    validations:
      required: false

  - type: checkboxes
    id: help-offered
    attributes:
      label: Can you help with this?
      options:
        - label: Yes, I'm willing to submit a PR
        - label: No, but I can provide feedback on drafts
        - label: No, I need someone else to handle this

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for similar documentation requests
          required: true
        - label: I have checked if this documentation exists elsewhere
          required: true
        - label: I have provided specific suggestions for improvement
          required: true
        - label: I have considered the target audience for this documentation
          required: true
