name: 🚀 Feature Request
description: Suggest a new feature or enhancement for zuki
title: "[FEATURE] "
labels: ["enhancement", "needs-discussion"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a new feature! Please fill out this form to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: Ex. I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe the main scenarios where this feature would be useful.
      placeholder: |
        Primary use case:
        Additional use cases:
        Target users:
    validations:
      required: true

  - type: textarea
    id: api-example
    attributes:
      label: Proposed API (if applicable)
      description: Provide a rough sketch of what the API might look like.
      render: zig
      placeholder: |
        const zuki = @import("zuki");
        
        pub fn example() !void {
            // Your proposed API usage here
        }
    validations:
      required: false

  - type: checkboxes
    id: priority
    attributes:
      label: Priority
      options:
        - label: Low - Nice to have
        - label: Medium - Would significantly improve the project
        - label: High - Critical for project success

  - type: checkboxes
    id: complexity
    attributes:
      label: Complexity Estimate
      options:
        - label: Small - A few hours of work
        - label: Medium - A few days of work
        - label: Large - Weeks of work
        - label: Extra Large - Major undertaking

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request here.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: I have provided clear use cases for this feature
          required: true
        - label: I am willing to help implement this feature (optional)
          required: false
