name: 🚄 Performance Issue
description: Report a performance problem or regression in zuki
title: "[PERFORMANCE] "
labels: ["performance", "needs-investigation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a performance issue! Please provide detailed measurements and reproduction steps.

  - type: textarea
    id: performance-problem
    attributes:
      label: What performance problem are you experiencing?
      description: A clear description of the performance issue (e.g., slow execution, high memory usage, etc.).
    validations:
      required: true

  - type: textarea
    id: expected-performance
    attributes:
      label: Expected Performance
      description: What performance characteristics did you expect?
    validations:
      required: true

  - type: textarea
    id: actual-performance
    attributes:
      label: Actual Performance
      description: What performance are you actually seeing?
    validations:
      required: true

  - type: textarea
    id: benchmark-results
    attributes:
      label: Benchmark Results
      description: Include relevant benchmark results, timing data, or profiling information.
      render: shell
      placeholder: |
        Benchmark: [name]
        Time: [duration]
        Memory: [usage]
        CPU: [usage]
    validations:
      required: false

  - type: dropdown
    id: regression
    attributes:
      label: Performance Regression?
      options:
        - "Yes, this worked better in a previous version"
        - "No, this has always been slow"
        - "Not sure"
    validations:
      required: true

  - type: input
    id: last-working-version
    attributes:
      label: Last Working Version (if regression)
      placeholder: e.g., 0.0.9
    validations:
      required: false

  - type: input
    id: os
    attributes:
      label: Operating System
      placeholder: e.g., Windows 11, macOS 13.0, Ubuntu 22.04
    validations:
      required: true

  - type: input
    id: architecture
    attributes:
      label: Architecture
      placeholder: e.g., x86_64, aarch64
    validations:
      required: true

  - type: input
    id: cpu
    attributes:
      label: CPU
      placeholder: e.g., Intel i7-12700K, Apple M2, AMD Ryzen 7 5800X
    validations:
      required: true

  - type: input
    id: ram
    attributes:
      label: RAM
      placeholder: e.g., 32GB DDR4-3200
    validations:
      required: true

  - type: input
    id: zig-version
    attributes:
      label: Zig Version
      placeholder: e.g., 0.12.0
    validations:
      required: true

  - type: input
    id: zuki-version
    attributes:
      label: zuki Version
      placeholder: e.g., 0.1.0
    validations:
      required: true

  - type: dropdown
    id: build-mode
    attributes:
      label: Build Mode
      options:
        - Debug
        - ReleaseFast
        - ReleaseSafe
        - ReleaseSmall
    validations:
      required: true

  - type: textarea
    id: reproduction-code
    attributes:
      label: Reproduction Code
      description: Minimal code that demonstrates the performance issue.
      render: zig
      placeholder: |
        const std = @import("std");
        const zuki = @import("zuki");

        pub fn main() !void {
            // Your performance test code here
        }
    validations:
      required: true

  - type: textarea
    id: measurement-steps
    attributes:
      label: How to Measure
      description: Instructions for reproducing the performance measurements.
      placeholder: |
        1. Step one
        2. Step two
        3. ...
    validations:
      required: true

  - type: dropdown
    id: impact
    attributes:
      label: Impact Assessment
      options:
        - "Critical - Makes the runtime unusable"
        - "High - Significantly impacts performance"
        - "Medium - Noticeable performance degradation"
        - "Low - Minor performance impact"
    validations:
      required: true

  - type: textarea
    id: profiling-data
    attributes:
      label: Profiling Data (if available)
      description: Include any profiling data such as call graphs, memory allocation patterns, hot paths, etc.
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any workarounds, related issues, or performance requirements for your use case.
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      options:
        - label: I have searched existing issues for similar performance problems
          required: true
        - label: I have provided measurable performance data
          required: true
        - label: I have tested with release builds (not debug)
          required: true
        - label: I have included reproduction steps
          required: true
        - label: I have profiled the code to identify bottlenecks (if possible)
          required: false
