---
name: ❓ Question
about: Ask a question about using zuki
title: '[QUESTION] '
labels: ['question', 'needs-response']
assignees: ''
---

## Question

**What would you like to know?**
Ask your question clearly and concisely.

## Context

**What are you trying to achieve?**
Describe your goal or use case.

**What have you tried so far?**
Include any approaches you've already attempted.

**Code context (if applicable):**
```zig
// Include relevant code that relates to your question
const std = @import("std");

pub fn main() void {
    // Your code here
}
```

## Environment

**System Information (if relevant):**
- OS: [e.g., Windows 11, macOS 13.0, Ubuntu 22.04]
- Zig Version: [e.g., 0.12.0]
- zuki Version: [e.g., 0.1.0]

## Research Done

**Documentation checked:**
- [ ] README.md
- [ ] API documentation
- [ ] Examples in the repository
- [ ] CONTRIBUTING.md

**External resources consulted:**
- [ ] Zig documentation
- [ ] Community discussions
- [ ] Stack Overflow
- [ ] Other async runtime documentation

**Similar issues/discussions:**
List any similar issues or discussions you found (but didn't fully answer your question).

## Additional Context

**Urgency:**
- [ ] Just curious
- [ ] Needed for current project
- [ ] Blocking immediate work

**Experience level:**
- [ ] New to Zig
- [ ] New to async programming
- [ ] Experienced with both
- [ ] Other: [specify]

## Checklist

- [ ] I have searched existing issues and discussions
- [ ] I have checked the documentation
- [ ] I have provided enough context for others to understand my question
- [ ] This is not a bug report (if it is, please use the bug report template)
