[book]
authors = ["Christian Brendlin"]
language = "en"
multilingual = false
src = "src"
title = "Zuki Async Runtime"
description = "High-performance async runtime for Zig — fast, cross-platform, and zero-cost by design"

[build]
build-dir = "book"
create-missing = true

[output.html]
default-theme = "navy"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/zuki-dev/zuki"
edit-url-template = "https://github.com/zuki-dev/zuki/edit/main/docs/{path}"
site-url = "/zuki/"
syntax-highlighting-theme = "base16-ocean"

[output.html.search]
enable = true
limit-results = 30
teaser-word-count = 30
use-boolean-and = true
boost-title = 2
boost-hierarchy = 1
boost-paragraph = 1
expand = true
heading-split-level = 3

[output.html.playground]
runnable = false
